# Generated by Django 6.0.1 on 2026-02-03 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('nombre_pistes', models.PositiveIntegerField()),
                ('artiste', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'CD',
                'verbose_name_plural': 'CDs',
            },
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('duree', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('realisateur', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'DVD',
                'verbose_name_plural': 'DVDs',
            },
        ),
        migrations.CreateModel(
            name='JeuPlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('editeur', models.CharField(max_length=200)),
                ('nombre_joueurs_min', models.PositiveIntegerField(default=2)),
                ('nombre_joueurs_max', models.PositiveIntegerField(default=4)),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jeu de plateau',
                'verbose_name_plural': 'Jeux de plateau',
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('nombre_pages', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque.cd')),
                ('dvd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque.dvd')),
                ('livre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque.livre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.membre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
            },
        ),
    ]
