# Generated by Django 6.0.1 on 2026-02-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='nombre_pages',
        ),
    ]
