# Generated by Django 6.0.1 on 2026-02-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0002_remove_livre_isbn_remove_livre_nombre_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='realisateur',
        ),
    ]
