# Generated by Django 6.0.1 on 2026-02-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0003_remove_dvd_realisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='auteur',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='auteur',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
