# Generated by Django 6.0.1 on 2026-02-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0004_alter_cd_auteur_alter_dvd_auteur_alter_livre_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='nombre_exemplaires',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dvd',
            name='nombre_exemplaires',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='livre',
            name='nombre_exemplaires',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
