# Generated by Django 6.0.1 on 2026-02-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0005_cd_nombre_exemplaires_dvd_nombre_exemplaires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='actif',
        ),
    ]
